if (require.main === module) throw new Error('Source reference only; private browser/login adapters are deliberately excluded.');
const fs=require('fs');
const path=require('path');
const {chromium}=require('playwright');
const dir=path.resolve(process.argv[3]||'drafts/2026-09-26/rewrite');
const map={mark1:['mark1','BLOG_ID_PLACEHOLDER'],mark2:['mark2','BLOG_ID_PLACEHOLDER'],mark3:['gomterior','BLOG_ID_PLACEHOLDER'],mark5:['mark5','BLOG_ID_PLACEHOLDER']};
const account=process.argv[2];
if(!map[account])throw Error('unknown account');
const [browserName,blogId]=map[account];
const result=JSON.parse(fs.readFileSync(path.join(dir,`${account}-repaired-save-result.json`),'utf8'));
const article=fs.readFileSync(path.join(dir,`${account}.md`),'utf8');
const expectedText=article.split(/\r?\n/).slice(1).map(x=>x.trim().replace(/^#{2,3} /,'').replace(/\*\*/g,'')).filter(x=>x&&!x.startsWith('!['));
const expectedImages=(article.match(/^!\[/gm)||[]).length;
const manifest=JSON.parse(fs.readFileSync(path.join(dir,'image-manifest.json'),'utf8'));
const expectedAi=manifest.jobs.filter(j=>j.account===account).map(j=>j.sourceType==='ai');
if(expectedAi.length!==expectedImages)throw Error(`${account}: manifest image count mismatch`);
const compact=x=>String(x).replace(/[\s\u200b]/gu,'');
(async()=>{
 const port=fs.readFileSync(path.resolve(__dirname,'../accounts/browser-runtime',browserName,'chrome/DevToolsActivePort'),'utf8').split('\n')[0];
 const browser=await chromium.connectOverCDP(`http://127.0.0.1:${port}`);
 const context=browser.contexts()[0];const before=new Set(context.pages());
 try{
  const page=await context.newPage();
  await page.goto(`https://blog.naver.com/PostWriteForm.naver?blogId=${blogId}&Redirect=Write&redirect=Write`,{waitUntil:'domcontentloaded',timeout:30000});
  const frame=page.frames().find(f=>f.url().includes('PostWriteForm'))||page;
  const cancel=frame.locator('.se-popup-button-cancel');
  if(await cancel.isVisible().catch(()=>false))await cancel.click();
  const count=frame.locator('[data-click-area="tpb*s.count"]');
  await count.waitFor({state:'visible',timeout:15000});await count.click();
  const rows=frame.locator('li.item__k1QHQ').filter({hasText:result.title});
  await rows.first().waitFor({state:'visible',timeout:20000});
  const records=await rows.evaluateAll(nodes=>nodes.map(x=>({title:x.querySelector('strong')?.innerText?.trim(),stamp:x.querySelector('span.date__fCMep')?.innerText?.trim()})));
  const oldTitle=manifest.articles[account].oldTitle;
  const oldCount=await frame.locator('li.item__k1QHQ strong').evaluateAll((nodes,t)=>nodes.filter(n=>n.innerText.trim()===t).length,oldTitle);
  if(oldTitle!==result.title&&oldCount!==0)throw Error('Old title still present: replacement not established');
  const matching=records.filter(x=>x.title===result.title);
  if(matching.length!==1)throw Error(`${account}: expected 1 exact titled draft, got ${matching.length}`);
  const current=matching[0];
  if(!current||!current.stamp)throw Error(`${account}: saved timestamp missing`);
  const row=rows.filter({has:frame.locator('span.date__fCMep',{hasText:current.stamp})});
  await row.locator('button.article_button__p0NRG').click();
  const content=frame.locator('.se-content');await content.waitFor({state:'visible',timeout:20000});
  await frame.waitForFunction(({title,images})=>document.querySelector('.se-title-text')?.innerText?.trim()===title&&document.querySelectorAll('.se-module-image').length===images,{title:result.title,images:expectedImages},{timeout:30000});
  const got=await frame.evaluate(()=>({title:document.querySelector('.se-title-text')?.innerText?.trim(),body:document.querySelector('.se-content')?.innerText||'',images:[...document.querySelectorAll('.se-module-image')].map(node=>({loaded:[...node.querySelectorAll('img')].some(img=>img.complete&&img.naturalWidth>0),ai:node.closest('.se-component')?.querySelector('button.se-set-ai-mark-button-toggle')?.classList.contains('se-is-selected')||false}))}));
  const missing=expectedText.filter(x=>!compact(got.body).includes(compact(x)));
  const wrongAi=got.images.filter((x,i)=>x.ai!==expectedAi[i]).length;
  if(got.title!==result.title||got.images.length!==expectedImages||missing.length||got.images.some(x=>!x.loaded)||wrongAi)throw Error(`${account}: persisted QA failed title=${got.title===result.title} images=${got.images.length}/${expectedImages} missing=${missing.length} unloaded=${got.images.filter(x=>!x.loaded).length} wrongAi=${wrongAi}`);
  const verified={status:'FINAL_DRAFT_SAVED_VERIFIED',account,title:result.title,newStamp:current.stamp,imageCount:got.images.length,aiImageCount:expectedAi.filter(Boolean).length,fieldPhotoCount:expectedAi.filter(x=>!x).length,bodyBlocksVerified:expectedText.length,verifiedAt:new Date().toISOString()};
  fs.writeFileSync(path.join(dir,`${account}-repaired-saved-list-verification.json`),JSON.stringify(verified,null,2));
  console.log(JSON.stringify(verified));
 }finally{for(const p of context.pages())if(!before.has(p)&&!p.isClosed())await p.close().catch(()=>{});await browser.close()}
})().catch(e=>{console.error(e.stack||e.message);process.exitCode=1});
